CREATE TABLE "GCG_6195_ESTACT" (
 "ORDER_NO" CHAR(7),
 "ORDER_LINE" CHAR(4),
 "QUOTE_NO" CHAR(7),
 "QUOTE_LINE" CHAR(4),
 "PART" CHAR(20),
 "QTY_QUOTE" DOUBLE,
 "LABOR_COST" DOUBLE,
 "OVERHEAD_COST" DOUBLE,
 "MATERIAL_COST" DOUBLE,
 "OUTSIDE_COST" DOUBLE,
 "LABOR_HOURS" DOUBLE );